Repository teamvolik/teamvolik, pull requests merged in 2022-03, with the labels that each got.

#11 Support git hooks (#2)
  .git-hooks/pre-commit
Labels: enhancement

#21 Feature/initial bot version
  .gitignore
  src/bot/main.py
  src/bot/utils/keyboards.py
  src/bot/utils/reply_list.py
  src/classes/game.py
  src/db/database.py
  test/db/test_database_games.py
  test/db/test_database_misc.py
  test/db/test_database_players.py
  test/db/test_database_registrations.py
Labels: enhancement

#24 Update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: hotfix

#27 Registration bug
  src/bot/main.py
Labels: bugfix

#22 Minor test improvements
  .coveragerc
  .github/workflows/test.yml
  setup.cfg
  src/classes/game.py
  src/classes/player.py
  src/classes/registration.py
  test/classes/__init__.py
  test/classes/test_games.py
  test/classes/test_players.py
  test/classes/test_registrations.py
Labels: enhancement

#29 Update readme
  .github/README_MISC/GUI_1.jpg
  .github/README_MISC/GUI_2.jpg
  .github/README_MISC/teamvolik.jpeg
  README.md
Labels: documentation

#30 Update requirements
  requirements.txt
Labels: documentation
